### ISSUE TITLE
Firebase API key is exposed

### ISSUE THREAD

**Issue by khammami** [ChinonsoIg/fuel-credit#1]
Hey @ChinonsoIg, you should not include [.env](https://github.com/ChinonsoIg/fuel-credit/blob/eefd2acb1af1d8c9022b5d02808893c0744add1b/.env) in your Git repo. 
Remove it and regenerate you firebase api key.

Use env vars of Vercel for your build and  deployment https://vercel.com/docs/concepts/projects/environment-variables

**Comment by ChinonsoIg** [comment]
Wow! Thanks a lot Khalil. Just realised it was not ignored by my .gitignore file.

    On Friday, March 31, 2023 at 01:45:48 PM GMT+1, Khalil Hammami ***@***.***> wrote:  
 
 


Hey @ChinonsoIg, you should not include .env in your Git repo.
Remove it and regenerate it.

Use env vars of Vercel for your build and deployment https://vercel.com/docs/concepts/projects/environment-variables
